### ISSUE TITLE
Error while running the tool

### ISSUE THREAD

**Issue by AshishDora** [Sambal0x/firebaseEnum#1]
Traceback (most recent call last):
  File "firebaseEnum.py", line 96, in <module>
    main()
  File "firebaseEnum.py", line 84, in main
    keyword_search.execute(args.mutations, args.keyword, args.threads)
  File "C:\Users\ashis\OneDrive\Desktop\Android PT\firebaseEnum\tools\keyword_search.py", line 115, in execute
    mutations = read_mutations(mutation_file)
  File "C:\Users\ashis\OneDrive\Desktop\Android PT\firebaseEnum\tools\keyword_search.py", line 22, in read_mutations
    with open(mutation_file, encoding="utf8", errors="ignore") as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/tools/fuzz.txt'

**Comment by shaky83** [comment]
You need to open script with any text editor and edit below code:

```
#Use included mutation file by default, or let user provide one
    parser.add_argument('-m', '--mutations', type=str, action='store',
                        default=script_path + '/tools/fuzz.txt',
                        help='Mutation. Default: tools/fuzz.txt')
```
                        
Add the full path in front of the '/tools/fuzz.txt', so it looks something like

```
#Use included mutation file by default, or let user provide one
    parser.add_argument('-m', '--mutations', type=str, action='store',
                        default=script_path + 'Users/xxxxx/Desktop/firebaseEnum/tools/fuzz.txt',
                        help='Mutation. Default: tools/fuzz.txt')
```
